---
-  name: Creating user repo
   user:
     name: "{{ aptly_user }}"
     shell: /bin/nologin

- name: Install aptly debian repository
  apt_repository:
    repo: 'deb http://repo.aptly.info/ squeeze main'
    state: present
    update_cache: yes

- name: Import aptly key
  apt_key:
    id: 2A194991
    keyserver: "{{ aptly_keyserver }}"

-
    name: Install necesarry packages
    apt: name={{ item }} state=present update_cache=yes
    with_items:
        - aptly={{ aptly_version }}
        - gnupg
        - "{{ aptly_webserver }}"

- name: Copy config file
  template:
    src: aptly.conf.j2
    dest: /etc/aptly.conf
    owner: root
    group: root
    mode: 0644

-
    name: Upload repository key
    copy:
        src: "{{ aptly_secret_key_path }}/{{ aptly_secret_key_file }}"
        dest: /tmp
        owner: "{{ aptly_user }}"
        group: "{{ aptly_user }}"
        mode: 0400
-
    name: Import repository key to gnupg
    shell: >
        ( gpg --list-secret-keys | grep -q "{{ aptly_secret_key_id }}" )
        || gpg --allow-secret-key-import --import /tmp/{{ aptly_secret_key_file }}

-
    name: Remove secret key from remote host
    file: path="/tmp/{{ aptly_secret_key_file }}" state=absent
-
    name: Create repositories
    shell: >
        (aptly repo list -raw | grep -q "{{ item.name }}" )
        || (
            aptly repo create \
                --comment "{{ item.comment|default('\"\"') }}" \
                --distribution "{{ item.distribution|default('main') }}" \
                --component "{{ item.component|default('main') }}" \
                "{{ item.name }}"
        )
    with_items: aptly_repositories
    when: aptly_repositories is defined
-
    name: Upload dummy package
    copy: src=dummy_0.1_all.deb dest=/tmp/
    sudo: yes
-
    name: Import dummy package to repository
    command: aptly repo add {{ item.name }} /tmp/dummy_0.1_all.deb
    with_items: aptly_repositories
    when: aptly_repositories is defined
-
    name: Publish repositories
    shell: >
        (aptly publish list | grep -q "{{ item.name }}")
        || aptly publish repo \
            --gpg-key "{{ aptly_secret_key_id }}" \
            --architectures "{{ item.architectures|default('amd64,i386') }}" \
            "{{ item.name }}" \
            "{{ item.prefix|default(item.name) }}"
    with_items: aptly_repositories
    when: aptly_repositories is defined

- name: Import keys of mirrored repos
  command: gpg --no-default-keyring --keyring trustedkeys.gpg --keyserver {{ aptly_keyserver }} --recv-keys {{ item }}
  with_items: aptly_mirror_keys 

- name: Create mirrors
  command: "aptly mirror create -architectures=amd64 -filter='{{ aptly_filter | join (\" | \") }}' {{ item.name }} {{ item.url }} {{ item.component }}"
  with_items: aptly_mirrors
  failed_when: False

- name: Update mirrors
  command: aptly mirror update {{ item.name }}
  with_items: aptly_mirrors

- name: Copy daily cronjob
  template:
    src: cron.j2
    dest: /etc/cron.daily/aptly
    owner: root
    group: root
    mode: 0700

- name: Copy apache config
  template:
    src: apache.j2
    dest: /etc/apache2/sites-available/aptly.conf
    owner: root
    group: root
    mode: 0644
  when: aptly_webserver == "apache2"

- name: Enable apache vhost
  command: a2ensite aptly.conf
  args:
    creates: /etc/apache2/sites-enabled/aptly.conf
  notify: restart apache2
  when: aptly_webserver == "apache2"

