---
-  name: Creating user repo
   user:
     name: "{{ aptly_user }}"
     shell: /bin/nologin

- name: Install aptly debian repository
  apt_repository:
    repo: 'deb http://repo.aptly.info/ squeeze main'
    state: present
    update_cache: yes

- name: Import aptly key
  apt_key:
    data: |
      -----BEGIN PGP PUBLIC KEY BLOCK-----
      Version: GnuPG v1

      mQENBFbn0iMBCACqn6Y+NGqRHFjalcqqlvaG9LZMU4iNHPXmpHIelPg0+wgGurF2
      EnoqwYP4bB7Y7olEhF3IRYntgvWPM3PxHHvX0HfQ2g+28g3uwqjfj5h9p0jTg+bT
      Qb6IUhUB7yDQy+a7nP+TuRuTAeMnPMyornZaI9Ch/lEUaHpxOchylD0QCgzFqLDj
      fEE7m+NqZ7ICnLnmCnP29mszv0HnnxbEuCSVipLBsUo1Jp8z0eLlpUUR3skBb1pX
      aX7jzYHSF2HOSdr9265IymFdJYLK174I9RYhcfOIPjkzh+hk32ojkL5txxd2Ry1y
      ks3S8bNQI9a9k6AY4h1SeuJz/iEMl5nnnQG1ABEBAAG0HEFuZHJleSBTbWlybm92
      IDxtZUBzbWlyYS5ydT6JAUEEEwECACsCGwMFCQPCZwAGCwkIBwMCBhUIAgkKCwQW
      AgMBAh4BAheABQJW59I2AhkBAAoJEJ4+U/GcfeRggu4H/j17j90a+VL7SC9/1eEa
      k26iJaNDrUb662kJSuOUZuI5xDTujdJXMbIWjNIIsY9akfoLeXmnMFdnraF7a3ht
      9ma+t8/KxPdB/KZZGfmbC0D0gkkbwgP0F+n3ChFT0V+Vb5lw49stTStFXSevvtZG
      Efp2zuhSJaCIMDAKEpolAoVwxeZv3CeumIco7ZgWvLLpWyDemdkK+JuX2mTK6mlZ
      TlFVpAcjTI2SULGw8ulWaU4uCjxZWlSl42NEeJ6wUM62Kd2kLJRACdg+VWVET1KQ
      4fOuzIy03cvoJAe3gB32e7wxS56xRkGNiFJMOg9BdljEloKQei2XKSjvk2VfqRLk
      v+u5AQ0EVufSIwEIAMe8wWmTbl7s2i76FLq+tE9klRQ8pVCjpizoHFYntVIjiHUL
      sHyXb44y7Zz54WINSEXB9IKZ7VgcuudnJ3dgmcPZ8KFThGdaUKY+VIl8MgQF8TlV
      LvVCM0H/a1qiPiUJ9yIPe0MGJuGLOABmuLe1w/6ZP2hr2NZM1SIMsTQlyDZXhw9o
      Gx1yBtF3ZLdtNzHB/5Wkf62vdWuEIPvTc4eQ6uMjeTLl+mz8UJHB0PDnsOLoQmC9
      +s4yKur7z3/JCW58phmkDRf6ceVBPxDPyXXsj67eSthe/m3C5WWL9fUjxi+GM0/g
      u9rxLB/zIzX8XSq8C05iB7CQ42bQe3tp11hciaEAEQEAAYkBJQQYAQIADwUCVufS
      IwIbDAUJA8JnAAAKCRCePlPxnH3kYBKDB/9yS+8arxK1Na8AF5ja7+imVWv2iz6R
      Q85XIHYqeh5ev6K3UQLywR/SxESviJLKwwg/wRj8o5je4CBWnSU2M6VHyBEOP2WD
      SWEwEjBPAuNNFLxqx17xAYjIgMVBctCxsmz5B8EughfardlBbwxAhH/BCjpcSacH
      r1n4uNh+MmQ8MD9fZ2Uu6JnkOcj0mAzBC52qf9wyeqLR9EQRnkIt3XoI6UvCuCv3
      YZHbdsKHllr/0OjDh1sj3L6lI7Cw6klyIs5SYCaKYDBipRXTcypAPAEoubuViSD+
      +rbSfLsUWdBWdzpdIyYbsyfb6IIBLxniXhuO9nqxoSa8YuIHYeVY/3YT
      =3Sjb
      -----END PGP PUBLIC KEY BLOCK-----


- name: Install necessary packages
  apt: name={{ item }} state=present update_cache=yes
  with_items:
      - aptly={{ aptly_version }}
      - gnupg
      - "{{ aptly_webserver }}"

- name: Copy config file
  template:
    src: aptly.conf.j2
    dest: /etc/aptly.conf
    owner: root
    group: root
    mode: 0644

- name: Check if key is already present
  command: gpg --list-secret-keys | grep -q "{{ aptly_secret_key_id }}"
  when: aptly_secret_key_id is defined
  register: key_present
  changed_when: False
  failed_when: False

- name: Upload repository key
  copy:
      src: "{{ aptly_secret_key_path }}/{{ aptly_secret_key_file }}"
      dest: /tmp
      owner: "{{ aptly_user }}"
      group: "{{ aptly_user }}"
      mode: 0400
  when: aptly_secret_key_id is defined and key_present.rc != 0

- name: Import repository key to gnupg
  shell: gpg --allow-secret-key-import --import /tmp/{{ aptly_secret_key_file }}
  when: aptly_secret_key_id is defined and key_present.rc != 0

-
    name: Remove secret key from remote host
    file: path="/tmp/{{ aptly_secret_key_file }}" state=absent
    when: aptly_secret_key_id is defined
-
    name: Create repositories
    shell: >
        (aptly repo list -raw | grep -q "{{ item.name }}" )
        || (
            aptly repo create \
                --comment "{{ item.comment|default('\"\"') }}" \
                --distribution "{{ item.distribution|default('main') }}" \
                --component "{{ item.component|default('main') }}" \
                "{{ item.name }}"
        )
    with_items: aptly_repositories
    when: aptly_repositories is defined

- name: Ensure import dir is present
  file:
    path: "{{ aptly_import_dir }}"
    state: directory
  when: aptly_repositories is defined

- name: Import packages to repository
  command: aptly repo add {{ item.name }} {{ aptly_import_dir }}
  with_items: aptly_repositories
  when: aptly_repositories is defined

-
    name: Publish repositories
    shell: >
        (aptly publish list | grep -q "{{ item.name }}")
        || aptly publish repo \
            --gpg-key "{{ aptly_secret_key_id }}" \
            --architectures "{{ item.architectures|default('amd64,i386') }}" \
            "{{ item.name }}" \
            "{{ item.prefix|default(item.name) }}"
    with_items: aptly_repositories
    when: aptly_repositories is defined

- name: Update published repos
  command: aptly publish update {{ item.distribution }} {{ item.name }}
  with_items: aptly_repositories
  when: aptly_repositories is defined

-
    name: remove nginx 'it works' page
    file: path=/etc/nginx/sites-enabled/default state=absent
    when: aptly_webserver == "nginx"
-
    name: Upload nginx configuration file
    template: src=nginx-aptly.conf.j2 dest=/etc/nginx/sites-available/aptly.conf owner=root group=root mode=644
    notify: restart nginx
    when: aptly_webserver == "nginx"
-
    name: Creating nginx configuration symlinks
    file: src=/etc/nginx/sites-available/aptly.conf dest=/etc/nginx/sites-enabled/aptly.conf state=link
    notify: restart nginx
    when: aptly_webserver == "nginx"

- name: Copy apache config
  template:
    src: apache.j2
    dest: /etc/apache2/sites-available/aptly.conf
    owner: root
    group: root
    mode: 0644
  when: aptly_webserver == "apache2"

- name: Enable apache vhost
  command: a2ensite aptly.conf
  args:
    creates: /etc/apache2/sites-enabled/aptly.conf
  notify: restart apache2
  when: aptly_webserver == "apache2"

- name: Import keys of mirrored repos
  command: gpg --no-default-keyring --keyring trustedkeys.gpg --keyserver {{ aptly_keyserver }} --recv-keys {{ item }}
  with_items: aptly_mirror_keys 
  when: aptly_mirrors is defined

- name: Create mirrors
  command: "aptly mirror create -architectures=amd64 -filter='{{ aptly_filter | join (\" | \") }}' {{ item.name }} {{ item.url }} {{ item.component }}"
  with_items: aptly_mirrors
  when: aptly_mirrors is defined
  failed_when: False

- name: Update mirrors
  command: aptly mirror update {{ item.name }}
  with_items: aptly_mirrors
  when: aptly_mirrors is defined

- name: Copy daily cronjob
  template:
    src: cron.j2
    dest: /etc/cron.daily/aptly
    owner: root
    group: root
    mode: 0700
  when: aptly_mirrors is defined
